[package]
name = "solana-bitcoin-spv-program"
version = "0.0.1"
description = "Solana Bitcoin spv parsing program"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
chrono = { version = "0.4.0", features = ["serde"] }
log = "0.4.2"
num-derive = "0.2"
num-traits = "0.2"
serde = "1.0.92"
serde_derive = "1.0.92"
solana-sdk = { path = "../../sdk", version = "0.18.0-pre0"}


[lib]
crate-type = ["lib"]
name = "solana_btc_spv_program"
